### ISSUE TITLE
Bad link from google

### ISSUE THREAD

**Issue by kid47** [thirstyice/abe-site#101]
Link to the template given to us by the techs (specifically a "template from Leslie") downtown shows up as second result when "William Aberhart school" is googled. Discovered by my sister, so could feasibly affect others as well. @gjwehnes, could you please request that this be taken down to avoid confusion?

**Comment by thirstyice** [comment]
Doesn't happen anymore

**Comment by Sartaglo** [comment]
IT HAS RETURNED!
http://projects.cbe.ab.ca/aberhart/b829/aberhart_templates_from_leslie/default.htm

Second result (after the actual website) when searching "William Aberhart High School Budget."

**Comment by thirstyice** [comment]
Not anymore

**Comment by Sartaglo** [comment]
Found it again, searching "cbe aberhart" on DuckDuckGo (http://www.duckduckgo.com): http://projects.cbe.ab.ca/aberhart/b829/aberhart_templates_from_leslie/default.htm

**Comment by kid47** [comment]
Considering that over the summer the site is going to be completely changed again and it'll be under a different url, it's really a non issue at this point
