### ISSUE TITLE
Switch social media and website survey?

### ISSUE THREAD

**Issue by thirstyice** [thirstyice/abe-site#104]
Because the RSS and survey only appear on the homepage, the right sidebar is full of stuff while the left sidebar is nearly empty.

**Comment by kid47** [comment]
I don't see any problems with that. We may want to be aware of when we put up this with regards to other changes though because otherwise people will begin to wonder what else has changed, get flustered, and we may create a problem for ourselves. Either that or we may just want to highlight that we've only changed this in an info box or something

**Comment by kid47** [comment]
Actually, that may be a good idea (and I know it may not be appropriate in this thread, but we can deal with that if it's actually a good idea): maybe we should create a change log, like with an app, to tell people what has changed and to let them know that we're working on it

**Comment by thirstyice** [comment]
We have one: github.
The problem is that nobody looks at it

**Comment by kid47** [comment]
I meant more like the "what's new" section that you find on the Google play store. Users don't want to have to shift through all our code and comments and figure out what actually made it through

**Comment by thirstyice** [comment]
They don't have to. We have commit messages.

**Comment by kid47** [comment]
Yea, but what parent who's having trouble with our website will be able to find the commits in the first place, or even discover that we're on github?

**Comment by thirstyice** [comment]
If you want to manually build and maintain a running tally of everything we do, with context, in language that is both informative and readable to parents, then the best place to do that, at least for now, would probably be the github wiki, and I invite you to create a page.
Further discussion of this matter should be moved to a new issue

**Comment by thirstyice** [comment]
Switching implementation dates between this and #102 because there are things to discuss:

Without making things really hard, implementing this would mean that the survey would be on all pages and the social media would only be on the home page. Are we still ok with this?

**Comment by thirstyice** [comment]
Never mind. Doing it the hard way. (Social media and crisis info will be universal, on the left and right respectively)

**Comment by thirstyice** [comment]
How about social media in the footer (something similar to new-new-ui)

**Comment by thirstyice** [comment]
Done
