### ISSUE TITLE
iframes

### ISSUE THREAD

**Issue by kid47** [thirstyice/abe-site#105]
We've been receiving a lot of comments about the iframes, a lot negative. People are wanting us to make pdfs appear in their own pages again, but another option which is used on d2l is to give them a button to pop it out of the page, so then it doesn't interfere with our original ideology for the site. Thoughts?

**Comment by thirstyice** [comment]
We would have to use the pdf import method in `pdf-prototype`
I'll start playng

**Comment by thirstyice** [comment]
Summary of findings:
* There is a native button to open a pdf in presentation mode (full screen), as long as we are not importing into an iframe
* There is also a native button to download the pdf, whether in an iframe or not
* Implementing a "pop-out" button seamlessly with existing buttons would be hard
Recommend implementing the method of `pdf-prototype' and seeing what happens

**Comment by gjwehnes** [comment]
Excellent work. Please place in a seperate branch, so that we can evaluate and show to various stakeholders

**Comment by kid47** [comment]
already located in branch 'pdf-prototype', but I'm having the same problem I believe I've shown you before: 
![capture-pdf-prototype](https://cloud.githubusercontent.com/assets/8888679/6053653/608d37bc-ac9f-11e4-8926-1345da12fbf1.PNG)
![capture](https://cloud.githubusercontent.com/assets/8888679/6053659/6cfbb82a-ac9f-11e4-82a5-a32447695eff.PNG)
This I what I get when trying to view a pdf in firefox.
If this has yet to be implemented throughout the site, could you please do that @thirstyice, so that we can make a pull request? I would myself, but I have no clue how it works and don't have the time at the moment to figure it out.

**Comment by thirstyice** [comment]
This will be implemented over the weekend in the master branch. Visually and functionally it is exactly the same as now, and maintaining in parallel would be extremely tedious.

**Comment by thirstyice** [comment]
This importation method is not compatible with tabs. Recommend finding ways to remove tabs where possible.

**Comment by kid47** [comment]
What do you mean by tabs? As in things opening in new tabs?

**Comment by thirstyice** [comment]
Importation method complete

**Comment by kid47** [comment]
Just for the record: did a quick test from the new method and IE still produces the same results when printing through the provided button. Not sure if this is a fix for that problem, but then again we were sure it would be one. Possible alternate solution: the button at the top of all iframes giving users the choice to 'pop' the PDF out of the page into a new tab (possibly to print)?

**Comment by thirstyice** [comment]
Which results does IE produce?

**Comment by kid47** [comment]
Same as shown to us by @gjwehnes. Not sure how to explain it

**Comment by thirstyice** [comment]
https://github.com/mozilla/pdf.js/issues/3983
Seems there's nothing we can do about the ie thing
