### ISSUE TITLE
Tabs vs better pdf importation

### ISSUE THREAD

**Issue by thirstyice** [thirstyice/abe-site#109]
For better pdf importation to be implemented, tabs have to be removed.
This is not very high-priority, but is required in order to give the users what they have asked for. (#105)
Here is a list of all the documents currently using tabs. Items can be checked off as the tabs are removed.
Tabs without pdfs do not have to be changed
- [x] /b829/aberhart/main/calendars/CSI.html
- [x] /b829/aberhart/about/contact/additional-staff.html
- [x] /b829/aberhart/about/contact/admin.html
- [x] /b829/aberhart/about/contact/contact.html
- [x] /b829/aberhart/about/contact/learning-leaders.html
- [x] /b829/aberhart/about/contact/principal-advisory-council.html
- [x] /b829/aberhart/about/contact/teachers.html
- [x] /b829/aberhart/student-activities/debate/forms.html
- [x] /b829/aberhart/student-activities/debate/welcome-info.html
- [x] /b829/aberhart/departments/languages/english/english.html
- [x] /b829/aberhart/departments/athletics/forms/forms.html
- [x] /b829/aberhart/departments/phys-ed/forms/forms.html
- [x] /b829/aberhart/departments/languages/french/french.html
- [x] /b829/aberhart/departments/athletics/general/friends-of-orange.html
- [x] /b829/aberhart/departments/athletics/general/general.html
- [x] /b829/aberhart/main/document-index.html
- [x] /b829/aberhart/about/parent-council/parent-council.html
- [x] /b829/aberhart/departments/phys-ed/phys-ed.html
- [x] /b829/aberhart/student-services/registration/grade-10-courses.html
- [x] /b829/aberhart/student-services/registration/grade-11-courses.html
- [x] /b829/aberhart/student-services/registration/grade-12-courses.html
- [x] /b829/aberhart/departments/phys-ed/schedules/schedules.html
- [x] /b829/aberhart/departments/languages/spanish/spanish.html
- [x] /b829/aberhart/departments/special-education/special-education.html
- [x] /b829/aberhart/student-services/guidance.html
- [x] /b829/aberhart/departments/athletics/teams/basketball.html
- [x] /b829/aberhart/departments/athletics/teams/field-hockey.html
- [x] /b829/aberhart/departments/athletics/teams/football.html
- [x] /b829/aberhart/departments/athletics/teams/rugby.html
- [x] /b829/aberhart/departments/athletics/teams/soccer.html
- [x] /b829/aberhart/departments/athletics/teams/swim-dive.html
- [x] /b829/aberhart/departments/athletics/teams/volleyball.html
- [x] /b829/aberhart/Templates/tabs.html
- [x] /b829/aberhart/transportation/transportation.html
- [x] /b829/aberhart/departments/phys-ed/venues/venues.html
- [x] /b829/aberhart/departments/fine-arts/wampa/wampa.html

**Comment by thirstyice** [comment]
Debate forms can probably be removed: One is from last school year, and the other one hasn't worked properly since March (yes, last march) and nobody has noticed.
Will ask next week

**Comment by thirstyice** [comment]
Departments/languages could be split into individual languages

**Comment by kid47** [comment]
I'm still fuzzy on what you mean by tabs. Could you please elaborate?

**Comment by thirstyice** [comment]
https://github.com/thirstyice/abe-site/wiki/Guidelines#tabs-within-pages

**Comment by kid47** [comment]
Oh, gotcha now. When you said tabs though I thought you meant window tabs. And I do read the guidelines, but there's really no explicit explanation of what they are included

**Comment by gjwehnes** [comment]
WAMPA can be made into a simple HTML page with links to individual pages hosting the various pdfs that are currently shown in the tabs.

**Comment by gjwehnes** [comment]
https://github.com/thirstyice/abe-site/pull/146
