### ISSUE TITLE
banner to be made taller

### ISSUE THREAD

**Issue by gjwehnes** [thirstyice/abe-site#113]
Based on feedback from various stakeholders:

The news slider has been very well received, but a long-standing sentiment is that the photos are too small. Now that we have dynamically resizing and have removed the title banner, there may be an opportunity to grow the news banner's vertical width.

As long as the news categories appear "above the fold" (i.e. visible without scrolling down) for the minimum resolution, we can utilize the space.

**Comment by thirstyice** [comment]
What do you mean? Vertical width? We can't apply any restrictions to resolution, unless you mean the minimum width? And that has no effect on height.

**Comment by kid47** [comment]
Vertical height I believe is what was meant. Just making the slider more square so that the accompanying pictures can be larger on larger resolution screens. Maybe we could make height a function of width so that I doesn't look like the aspect ratio is weird?

**Comment by thirstyice** [comment]
What if the window it tall and skinny?

**Comment by kid47** [comment]
That's why it would be a function of width, so that it doesn't look weird in that situation

**Comment by thirstyice** [comment]
How do you propose we balance the image with any surrounding text?

**Comment by kid47** [comment]
Keep the percentage that the photo fills up now and scale everything around it?

**Comment by thirstyice** [comment]
What about keeping the news categories above the fold?

**Comment by kid47** [comment]
Max height? I'm not sure how we would do that, cause for a main page it's almost more important not to have a fold to keep things quick and simple for the user

**Comment by thirstyice** [comment]
Unfortunately max-height does not care about aspect ratio.

**Comment by kid47** [comment]
But how else would we prevent the fold?

**Comment by thirstyice** [comment]
We really can't

**Comment by kid47** [comment]
How about if max height of the container(or body, whichever) is 100%, and then max height of the slider is 30%? (Give or take whatever for the values) then the slider would get taller as the window gets taller, and would follow the current rules for horizontal resizing

**Comment by thirstyice** [comment]
Then the slider would have a scroll bar if the window gets too wide

**Comment by kid47** [comment]
Or if the content were too tall. Well darn, I'm out of ideas

**Comment by thirstyice** [comment]
Conclusion: though image sizes can scale dynamically, the news headers cannot be kept above the fold.
Discussion complete

**Comment by kid47** [comment]
Can we ignore the dynamic height and just simply boost the height a bit for it? That should satisfy the stakeholders

**Comment by kid47** [comment]
Thanks
