### ISSUE TITLE
grad info

### ISSUE THREAD

**Issue by kid47** [thirstyice/abe-site#116]
This is what's showing:
![download_20150220_221107](https://cloud.githubusercontent.com/assets/8888679/6312936/782f8e14-b94d-11e4-9a3c-202cfa567d5e.jpeg)
Not even sure how...

**Comment by thirstyice** [comment]
Because you hit the rotate button accidentally. It doesn't load like this normally

**Comment by kid47** [comment]
This wasn't me, and they didn't just got the Trieste button, because it's not only upside down, it's reversed

**Comment by kid47** [comment]
I'm not able to replicate it either though

**Comment by thirstyice** [comment]
It's rotated 180 degrees

**Comment by kid47** [comment]
Try to turn your screen and read it. You'll see what I mean

**Comment by thirstyice** [comment]
... That's funky

**Comment by kid47** [comment]
See my point?
