### ISSUE TITLE
Topmenu deletions

### ISSUE THREAD

**Issue by thirstyice** [thirstyice/abe-site#121]
As outlined in #120, there may soon be another area in the topmenu. Unfortunately, there isn't enough room for another area in the topmenu. So which area has to go?
Suggestions for merging, deleting and/or reshuffling content.
**Nothing in this issue should be implemented. It is theoretical only**

**Comment by kid47** [comment]
I would say we just make the main width larger to compensate

**Comment by thirstyice** [comment]
That is the backup, but I was looking for potential ways to not do that.

**Comment by kid47** [comment]
Content wise, I would say we pretty much have our hands tied. Too many people think that their content should have something in the top bar already, and so if we merge areas that are already full, I would imagine there'll be backlash

**Comment by thirstyice** [comment]
Can we go over what a suggestion looks like? It looks like this:
"Fees and transportation could be merged; they are both nearly empty and they both have to do with money and forms. The title could be fees/forms."

Nobody cares about transportation.

**Comment by kid47** [comment]
You also labeled this as a discussion, and I personally think that there's too much fiddling to go through to merge two top menu categories. If you want to sort it out with admin, go for it, but otherwise, the original plan that was talked about was just adding it to the top menu

**Comment by thirstyice** [comment]
It was meant as a discussion about which areas could be merged. If we just add an area to the topmenu without getting rid of anything else, everyone will want an area to themselves, and people who have been refused an area in the past will be somewhat unhappy. The only "fiddling" required to merge the categories is to move the files, plus one copy and paste.

**Comment by kid47** [comment]
Then saying I don't think any can be merged is still viable. I think you're overlooking the proposals and negotiations with admin to move existing things around. We've already been approved to put the learning commons in the top bar however

**Comment by thirstyice** [comment]
We'll cross that bridge when we come to it

**Comment by gjwehnes** [comment]
"Fees and Waivers" and "Transportation" are mandated from the central office. Even if admin was onboard with it (and they are, we discussed it just now), it is a non-started. Unfortunately, because we all agree that they shouldn't be their own super-category.

Agreed with kid47, several entities within the school are angling to be promoted to the nav bar. I tell them to join the line-up.

Is it at all possible to play with the button size on the nav bar? the margins are pretty generous

Also, we may be able to remove the student from "activities" and "services".

All that said, "standard" design theory would state that we should have no more than 7-8 items in the nav bar.  We are already at the maximum

**Comment by kid47** [comment]
I do like the margin reduction idea, but is there any reason why we couldn't put it in student services? Are there to many menu items or something for a drop down?

**Comment by gjwehnes** [comment]
student services is already a bit of a catch-all (guidance, career centre, learning centre), and yes, too many categories

**Comment by gjwehnes** [comment]
We may also consider removing the "about us" super category. School council will be moved out from there (new issue to follow soon), and the contact information pages could probably also be added to the home menu context menu. The school profile is a cut-and-paste job from the CBE's school profile, and could simply be reduced to a link to said external profile on the RHS external links list.

**Comment by kid47** [comment]
I would love to have that gone because there's so little in it and everyone who wants to find something that's in there looks elsewhere, but are we allowed to? I would have thought that, out of everything, that would be the one to be mandated by downtown

**Comment by thirstyice** [comment]
Do we still know what is mandated by downtown? It's been a year, during which time they redid their own website, is it possible that their requirements have changed?

**Comment by gjwehnes** [comment]
Will check

**Comment by gjwehnes** [comment]
We have the go-ahead to remove the "transportation tab". Also, "about us" can become "contact us".
