### ISSUE TITLE
School Council to move to home context menu

### ISSUE THREAD

**Issue by gjwehnes** [thirstyice/abe-site#123]
As per request from admin. 

This may also allow us to rid the nav bar of the "about" category (or at least rename it to contact). See discussion in issue #121 

At the same time the folder and file names should be updated to reflect that the Parent Council is now named the School Council

**Comment by kid47** [comment]
...are we allowed to say that we called this a long time ago? I think it was at the beginning of the year that I wanted to do this. Is my branch where I already implemented this still around?

**Comment by thirstyice** [comment]
It was deleted. I restored it. The branch was made before resizing content or better areamenus were implemented, so updates are required. PR #88

**Comment by kid47** [comment]
If we try to merge, won't it not affect the look? I'm not sure how much the merge will want to change

**Comment by thirstyice** [comment]
There are merge conflicts anyway. Starting from scratch is the way to go. With the new areamenu importation, all you have to do is move the files and cut/paste the areamenu links and it's done.

**Comment by kid47** [comment]
It wasn't that simple when I did it originally

**Comment by thirstyice** [comment]
No, which is why there had to be a separate branch, and why starting from scratch would be easier than modifying the existing branch.

**Comment by kid47** [comment]
OK. Go for it
