### ISSUE TITLE
JavaScript/Jquery broken

### ISSUE THREAD

**Issue by kid47** [thirstyice/abe-site#124]
This is what I see when I view the browser through mobile chrome. Extends off to the right, farther than the site width as well. Yet to test on other systems, but is not a "need to clear the cache" issue.
![screenshot_2015-03-01-14-24-48](https://cloud.githubusercontent.com/assets/8888679/6432913/38ad4bcc-c01f-11e4-9f53-b7b1f92d3392.png)

**Comment by thirstyice** [comment]
Could not replicate. What is your configuration?

**Comment by kid47** [comment]
Standard(default) configuration for js. Not sure why it would give me that then. Do we have a noscript message? Or would that not trigger in this case?

**Comment by thirstyice** [comment]
That text is not a part of jquery. I think it's a chrome issue.

**Comment by kid47** [comment]
Seems to be. Looks to me like that script could be coming from the search bar, but I see no reason for it. I feel like we missed some quotation marks somewhere or something like that

**Comment by thirstyice** [comment]
Closing: Not our issue
