### ISSUE TITLE
school council updates

### ISSUE THREAD

**Issue by gjwehnes** [thirstyice/abe-site#129]
-update draft minutes for 23 Feb (see gjwehnes for file)
-change next meeting to March 16th and indicate that this is a change of date from the previous date of March 30th to accommodate a visit from our School Trustee.

**Comment by gjwehnes** [comment]
to be assigned to DD when he is added as contributor

**Comment by thirstyice** [comment]
Who is that?

**Comment by owmygreenmatter** [comment]
sounds good, i'll get on it

**Comment by gjwehnes** [comment]
assigned to @owmygreenmatter
