### ISSUE TITLE
grad - "did you miss us" link

### ISSUE THREAD

**Issue by gjwehnes** [thirstyice/abe-site#130]
Post the attachment on our web with Grad information.  Note: this is for early grad students to access who are not now attending but will be graduating
![did-you-miss-us-link](https://cloud.githubusercontent.com/assets/6045608/6586370/9ca81b04-c73e-11e4-923a-f2004fb0862c.jpg)

**Comment by gjwehnes** [comment]
to be assigned to JW

**Comment by thirstyice** [comment]
Who is that?

**Comment by kid47** [comment]
People we're recruiting I guess

**Comment by thirstyice** [comment]
Ok...

**Comment by kid47** [comment]
You know about as much as I do about who the acronyms actually stand for. I'm just assuming this is an intro project for before we give them write permissions

**Comment by thirstyice** [comment]
I would agree, but in #129 it says *"to be assigned to DD when he is added as contributor"*
That, to me, implies a skipping over of the vetting process.

**Comment by kid47** [comment]
It implies the same thing to me as well, I was just hoping it was misworded

**Comment by thirstyice** [comment]
Me too

**Comment by gjwehnes** [comment]
This was just a way for me to communicate who was going to address these issues. I just didn't want to use actual names (FOIP issue), and neither DD or JW are yet on our list of contributors. Thus, we can either have them provide a solution and then add them or first add them.

**Comment by kid47** [comment]
Is one of them @owmygreenmatter?

**Comment by gjwehnes** [comment]
could be, I have not seen their user names. they are both in the CS20 class, sitting in the back corner

**Comment by kid47** [comment]
Then yea, I think that's one of them.

**Comment by thirstyice** [comment]
Ok

**Comment by owmygreenmatter** [comment]
just to clarify for everyone: i'm DD and JW is the other guy who'll be appearing soon (he's got a great screen name but it currently escapes me). we're both cs20 recruits, yeah

**Comment by gjwehnes** [comment]
To be implemented within an iFrame. A link at /main/news/upcoming/graduation-2015.html  (``Graduation Ring Order Information``) can point to it.

**Comment by gjwehnes** [comment]
assigned to @owmygreenmatter

**Comment by Bigbobo558** [comment]
I am the JW.

**Comment by thirstyice** [comment]
Why does it have to be in an iframe?

**Comment by kid47** [comment]
It assures people it's not an ad? I'm not sure

**Comment by thirstyice** [comment]
If it's in an iframe, the link will open in that iframe.

**Comment by Bigbobo558** [comment]
Wehnes explained it to me that we are not trying to put out the advertisement as an advertisement but rather as an information picture.

**Comment by kid47** [comment]
I agree that that's the best way to go at it, but it's just hard to create that feeling since it is an ad.we were just wondering how you would link to their website from it, because if the photo has a link embedded, their site would open within our iframe

**Comment by gjwehnes** [comment]
The photo does not have a link embedded. As Bigbobo558 mentioned, I did not want a 3rd party advertisement directly on one of our pages.
