### ISSUE TITLE
google search - document titles are cryptic

### ISSUE THREAD

**Issue by gjwehnes** [thirstyice/abe-site#131]
when googling ``grad``
![google search](https://cloud.githubusercontent.com/assets/6045608/6586893/68f6254e-c743-11e4-9e5b-3d19484c10a3.png)
 note "Graduation 2006..." and "Front row (left-right)...". 

These titles appear to be coming from the Title attribute of the PDF forms. We will need to sweep through and update these.

**Comment by gjwehnes** [comment]
note - grad documents already updated, but not yet pushed (pending branching of issue 121

**Comment by thirstyice** [comment]
We can't do anything about this, these titles are all of pdf documents, which are created by admin

**Comment by kid47** [comment]
I guess we could rename them ourselves

**Comment by thirstyice** [comment]
Only with a pdf editor

**Comment by kid47** [comment]
Word does the trick

**Comment by thirstyice** [comment]
Word is a thing I do not have. Editing the title will work for now, but we'll have to edit each new pdf from admin.
I recommend at least asking admin to update their titles

**Comment by gjwehnes** [comment]
On a PC at least you can edit the "title" attribute through the file explorer.

We also do have Acrobat in the lab.

**Comment by gjwehnes** [comment]
This is an additional reason for all document owners to start using the most up-to-date versions of documents when modifying. I mention this here mostly as a note to myself, as this involves finding a mechanism whereby all document holders actually do so. Many of the PDFs derive from Word documents that are <i>not</i> in a repository of any sort (i.e. all over the place)

**Comment by thirstyice** [comment]
Ok, but we can't do anything about it here.
Closing
