### ISSUE TITLE
Max-width slider

### ISSUE THREAD

**Issue by gjwehnes** [thirstyice/abe-site#137]
EDIT by @thirstyice: **This issue was originally only about max-width**

With the dynamic resizing, this was not addressed. We are still getting complaints that our page is too wide on certain monitors.

Will provide further clarifications tomorrow (i.e. specs for max_width); added now so that it does not get lost in the shuffle.

**Comment by thirstyice** [comment]
There is one: it's 1900px, see #122

**Comment by thirstyice** [comment]
How about a slider somewhere that would allow people to manually adjust max-width?

**Comment by kid47** [comment]
Ohhhhhhhh, I like that... I don't think that would be possible to store for each individual user though unless you got really fancy with posts and gets

**Comment by kid47** [comment]
Or there's some way you can use cookies in jquery

**Comment by thirstyice** [comment]
https://github.com/js-cookie/js-cookie

**Comment by kid47** [comment]
....I needed this a long time ago, could not find it

**Comment by thirstyice** [comment]
What scale should the slider have? Where should we put it?

**Comment by kid47** [comment]
Over top or under external links? And then it just fills the right hand side, we can have a pop up explaining what it does that's controlled by a booleanViewed in the cookie, and then it can toggle from our old min width to our current max width? That's probably what I would do. And then default we can maybe set to 1600? Any objections to that?

**Comment by thirstyice** [comment]
I suspect the slider might be too small there, but we'll see

**Comment by Bigbobo558** [comment]
If the max width could be set to 1080 and a background be set for anything beyond that, I suspect that would look pretty great. It would give quite a bit of width for viewing, while not stretching it too much. Just an idea.

**Comment by thirstyice** [comment]
The background would require that we add an element to all the webpages in the repo.
Why 1080px? That's smaller than an iPhone 5 in landscape.

**Comment by kid47** [comment]
Also, we took away the width that small specifically so that we could stretch it and make it feel less cramped and to accommodate different screen sizes. That would also completely negate all the effects of the changes to the website as it's only 20px wider that what we had before we implemented the dynamic layout.
As for suggestions, just make max width >1600px? Other than that, we could include the slider in a separate page and link to it as a kind of setting.

**Comment by kid47** [comment]
And the background before was quite frankly one of the most common complaints that we got about the design in the website survey

**Comment by thirstyice** [comment]
It would be a little weird to have a page with just a slider. Maybe under the news?

**Comment by kid47** [comment]
Well, theoretically we could do a settings page and then have more options as well, like backdrops colour or something. Maybe that's in the future though. For now, I don't see anything wrong with it being under news as long as it doesn't span the full div

**Comment by thirstyice** [comment]
What do you mean "span the full div?" Like be the full width of content?
Why would that be bad?

**Comment by kid47** [comment]
I think it would be too big. I'd make it like 50% width, because otherwise you'll have to slide the pointer too far too adjust it properly

**Comment by thirstyice** [comment]
I see. Probably a pixel width would be better though so that the size doesn't depend on the very setting you are changing. I could see that causing problems.

**Comment by kid47** [comment]
Good catch

**Comment by thirstyice** [comment]
Work is in `width-slider`.
Also, this is really cool. Playing highly recommended.

**Comment by thirstyice** [comment]
I don't see this being useful on a mobile interface, so the slider will be hidden on those OSs

**Comment by thirstyice** [comment]
Done.

**Comment by thirstyice** [comment]
Any further discussion will be moved to pr #148 
Closing.
