### ISSUE TITLE
Move CSI out of calendars?

### ISSUE THREAD

**Issue by thirstyice** [thirstyice/abe-site#139]
Now that it includes a description it's not just a calendar any more.
Also related to #109

**Comment by kid47** [comment]
Logically though, I think that's where people will look for it. I'm not sure about that one

**Comment by Bigbobo558** [comment]
I think it would make more sense to put CSI under the programs section, considering how it is a program I believe.

**Comment by kid47** [comment]
It's not a program though. It's more a service if anything

**Comment by Bigbobo558** [comment]
Yeah, woops. It actually would fall under that category. In any case, it doesn't fit in any more where it is, it grew up.

**Comment by gjwehnes** [comment]
agreed, let's move it to student services / CSI, and add a submenu item linking to a page with iframe for each of the PDFs

**Comment by Bigbobo558** [comment]
Created a pull request for this.
