### ISSUE TITLE
Film fest posters not in wrapper

### ISSUE THREAD

**Issue by thirstyice** [thirstyice/abe-site#144]

**Comment by gjwehnes** [comment]
True enough, but also consistent with how other photos in the banner are implemented,

As Film Fest is done, this issue will be obsolete by the end of today, when the item is removed. However, this issue can serve as a discussion on whether banner items should also be wrapped in a PDF.

**Comment by kid47** [comment]
The difference was though that the items that we're doing that with were photos that were already displayed. We were simply giving the option to them to view it separately in a bigger size, whereas the PDF was not displayed in site by default, which wasn't consistent with other PDFs

**Comment by thirstyice** [comment]
Aaaaand film fest is over.
