### ISSUE TITLE
Link to fees and forms broken

### ISSUE THREAD

**Issue by kid47** [thirstyice/abe-site#151]
Both in published and unpublished versions

**Comment by kid47** [comment]
on second inspection: our home file for that seems to be missing. @thirstyice, you got a backup?

**Comment by thirstyice** [comment]
It's a pdf, the link wasn't updated until b3fff854aa47981c248ab641c014a124550eef76

**Comment by thirstyice** [comment]
... But then @gjwehnes reverted it in 397a241345cd878a21ae9b27df92a59b08df27bf

**Comment by thirstyice** [comment]
Fixed
