### ISSUE TITLE
documents displayed in iFrame are cached in Chrome

### ISSUE THREAD

**Issue by gjwehnes** [thirstyice/abe-site#67]
Not necessarily a bug, more of an interface problem.

Documents displayed in iFrame are often cached in Chrome. This is causing a fair bit of grief, as documents that are often updated (e.g. student bulletin) appear out of date.

One potential workaround is have users manually clear their browsing data (cached images and files). This can be posted on the home page

However, it would be best if we can find a programmatic solution (or at least an understanding of how to avoid this problem)

**Comment by thirstyice** [comment]
Probably chrome is not caching the viewer or the iframes, but the pdfs. The only option then would be to modify the server header.
Good luck getting downtown to change their settings.

**Comment by thirstyice** [comment]
Actually, after getting familiar with the inner workings of pdf.js ( #149 ) it is extremely unlikely that chrome is caching the pdf, in which case this issue should no longer happen after the new pdf method was implemented.
Closing with fingers crossed.
