### ISSUE TITLE
new-new-ui breaks in mobile chrome

### ISSUE THREAD

**Issue by kid47** [thirstyice/abe-site#95]
Gives me this once in every two reloads-ish. Fairly reproduce able as far as my phone is concerned (nexus 5 with newest version of chrome for mobile)
![screenshot_2015-01-02-08-29-17](https://cloud.githubusercontent.com/assets/8888679/5597126/360b7544-925a-11e4-8129-49d91fe0b218.png)

**Comment by kid47** [comment]
Also breaks in mobile safari in a different way, but unfortunately I don't have photos for it. Basically the java script looks like it fails and all the menus are stacked on top of one another instead of having the one sliding one.

**Comment by thirstyice** [comment]
Breaks in both versions of safari, and for a different reason than in chrome

**Comment by thirstyice** [comment]
Splitting this issue in two because of differing causes

**Comment by thirstyice** [comment]
Issue for safari is #100

**Comment by thirstyice** [comment]
Does this still happen?

**Comment by kid47** [comment]
Are we still going to try it?

**Comment by thirstyice** [comment]
Probably not; it's buggy, doesn't work on all platforms, and people don't seem very fond of it.
