### ISSUE TITLE
iframes do not scroll in mobile safari

### ISSUE THREAD

**Issue by kid47** [thirstyice/abe-site#96]
Unfortunately no pictures, but specifically observed for the survey's iframe. could only see the firstbit an no option to scroll

**Comment by thirstyice** [comment]
This bug is present in desktop safari as well. Investigating.

**Comment by kid47** [comment]
Does not seen to be present in all versions of safari as we have had people reply to the survey using safari recently

**Comment by thirstyice** [comment]
This is just the survey, not the website

**Comment by kid47** [comment]
I can't find a fix for it. should i just push a note at the top to apologize if they can't scroll?
