### ISSUE TITLE
New RSS feed

### ISSUE THREAD

**Issue by gjwehnes** [thirstyice/abe-site#98]
CBE has updated their RSS feedbox code. The snippet below is their implementation. It may need to be formatted to meet our own guidelines.

Note: The RSS does not need to appear on every page, only the home page.

				<table id="rss">
				  <tr>
				    <th>CBE News</th>
			      </tr>
				  <tr>
				    <td><div class="rssfeedbox">
				      <script src="http://feeds.feedburner.com/CalgaryBoardOfEducationNews?format=sigpro" type="text/javascript" ></script>
				      <noscript>
				        <p>Subscribe to RSS headline updates from: <a href="http://feeds.feedburner.com/CalgaryBoardOfEducationNews"></a><br/>
				          Powered by FeedBurner</p>
			          </noscript>
				      <div class="subscribe"> <a href="http://feedburner.google.com/fb/a/mailverify?uri=CalgaryBoardOfEducationNews" target="_blank" >Sign up for  CBE RSS by Email</a> <br />
				        <a href="http://feeds2.feedburner.com/CalgaryBoardOfEducationNews?format=html" target="_blank">Subscribe by RSS</a></div>
				      </div></td>
			      </tr>
			  </table>

**Comment by kid47** [comment]
On It

**Comment by kid47** [comment]
Probably should have been put in it's own branch first, but done anyways

**Comment by thirstyice** [comment]
This has not been fixed, it has been patched. Real fix is in progres

**Comment by kid47** [comment]
What did I miss? It uses the same code style and classes as before and all the other RSS feeds have been removed

**Comment by thirstyice** [comment]
Padding has changed and some classes are no longer required. There is a gap between the feed and the border of the links. The links do not follow our guidelines. The code is no longer is its best possible state
